version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: techassets-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techassets
      MYSQL_USER: techuser
      MYSQL_PASSWORD: techpass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
